### ISSUE TITLE
option to auto-generate embedder code: //goki:embedder

### ISSUE THREAD

**Issue by rcoreilly** [goki/goki#4]
I ended up writing this code in several places in GoGi -- would be nice to have it auto-gen:

```Go
type ActionEmbedder interface {
	AsAction() *Action
}

func AsAction(k ki.Ki) *Action {
	if k == nil || k.This() == nil {
		return nil
	}
	if ac, ok := k.(ActionEmbedder); ok {
		return ac.AsAction()
	}
	return nil
}

func (ac *Action) AsAction() *Action {
	return ac
}
```

**Comment by kkoreilly** [comment]
You argued against this very heavily previously; why the sudden reversal?

**Comment by rcoreilly** [comment]
there were many more pure Embeders vs. existing interfaces (which could have the AsX added to them, and are not suitable for auto-gen).

**Comment by kkoreilly** [comment]
Done in a003ca6ee5efef7bd64f5663a3129ac5074e6272.
