### ISSUE TITLE
Fix icon resizing on zoom settings changes

### ISSUE THREAD

**Issue by rcoreilly** [goki/goki#632]
Unclear why -- some kind of min size factor somewhere.

Also button labels go to multi-line during zooming -- prior size alloc is being used?

**Comment by kkoreilly** [comment]
This is better now but there are still some issues in which it does not work correctly

**Comment by kkoreilly** [comment]
One case where this doesn't work correctly is when you move a window from a 1080p monitor to a 4k monitor (the icons stay small). Also, we need to figure out our 4k scaling approach more broadly.
